# Voll.Med API init
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voll-med
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: voll-med
        image: leonardosartorello/vollmed:v7
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: MYSQL_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: MYSQL_ROOT_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: dados
              key: REDIS_PORT
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /paciente
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

# ---
apiVersion: v1
kind: Service
metadata:
  name: vollmed
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
# ---
apiVersion: v1
kind: Service
metadata:
  name: vollmedlb
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
# Voll.Med API end



